### ISSUE TITLE
Which representation to follow?

### ISSUE THREAD

**Issue by tekrajchhetri** [brain-bican/models#93]
We were having a discussion on which representation to follow. @puja-trivedi and @djarecka was suggesting the second representation as it might be consistent  existing projects. However, @patrick-lloyd-ray and I align with the first approach.

Now the question is to @satra and @lydiang which approach to follow? 

**Note:** We don't necessarily need to generate the _UUID_, we can use the ORCID id with _ORCID_ prefix as <ORCID:0000-0000-0000-0000> as suggested by @puja-trivedi. This also means we make ORCID mandatory.

**Representation 1:**

```
@prefix : <http://example.org/ontology/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<UUID:1234-5678-9101> rdf:type :Person ;
                       :hasName "Alex" ;
                       :hasLastName "Doe" ;
                       :contributesTo <assertion-5678> ;
                       :hasORCID <0000-0000-0000-0000> ;
                       :hasResearchGate <Alex-Doe>;
                       :hasGoogleScholar <QlkwmPIABAAJ>.

<0000-0000-0000-0000> a OrcidIdentifier.

<Alex-Doe> a ResearchGateIdentifier.

<QlkwmPIABAAJ> a GoogleScholarIdentifier.


<assertion-5678> rdf:type :Assertion ;
                       :has_annotation "Sun is hot" .
```

**Representation 2:**

```
@prefix : <http://example.org/ontology/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<0000-0002-1825-0097> rdf:type :Person ;
                       :hasName "Alex" ;
                       :hasResearchGate "Alex-Doe";
                       :hasGoogleScholar "QlkwmPIABAAJ";
                       :contributesTo <assertion-5678> .

<assertion-5678> rdf:type :Assertion ;
                       :has_annotation "Sun is hot" .
```

**Comment by djarecka** [comment]
I think there are 2 main questions:
- do we need/want to have class for all `Identifiers`
- do we want to have entity id based on unique identifiers like `orcid` (yes, that's requires decision what is the "main identifier" that can be required)

I personally think that using orcid as the `id` (and not some other "random" unique identifier) make sense and is consistent with what we did for `library_generations` etc.

Re. first questions: I don't see big value (at least for now) to have classes for identifiers. But if we find good reason, we could add it

**Comment by tekrajchhetri** [comment]
The `Identifiers` mentioned by @djarecka are discussed in [this GitHub issue](https://github.com/brain-bican/models/issues/89), where they were initially proposed.

**Comment by satra** [comment]
representation 1 is imposing the constraint that the value of the property has to be a uri, not just a string. a uri does not have to belong to a class (i.e. one does not have to say its a DOI or ORCID). but if one can, one could. 

representation 2 also requires the identifier to be a uri (since a subject and a predicate in a triple have to be uris, they cannot be literals). 

in general, i'm a bigger fan of rep 1. i.e. associations that link identifiers rather than making the identifier be the node on which properties are hung. that being said, i don't think there is a general rule. this is a data model question about the objects that are being modeled. 

for example, 
1. if an id represents a person as in 2, you can never have a property called age, you can have date of birth. 
2. if you need to edit a record, it's easier to invalidate a previous record and add a new one than to invalidate a property of a record. so one could simply mint a new UUID and create a new record and simply say that this invalidates the previous one, without losing all the connected information and providing provenance. 

rep 1 also allows for some of those properties to be not filled, while rep 2 makes some id mandatory. this makes me lean towards rep 1 for this particular model of a person and it lends itself to database schemas and property graphs as well. in relation to dorota's second question, we can still impose requirements on properties in this model, but we can adjust those requirements over time. let's say we moved from orcid to some other id in the future. doable but a generally challenging database operation.

my vote would be for rep 1, but the following set of triples are not essential, but nice to have.

```
<0000-0000-0000-0000> a OrcidIdentifier.
<Alex-Doe> a ResearchGateIdentifier.
<QlkwmPIABAAJ> a GoogleScholarIdentifier.
```

**Comment by djarecka** [comment]
@satra - my reasoning was based on the experience with the bican models we already have. So do you think that we should change this for other models to be consistent? And just create a `NIMPIdentifier` class etc.?

One more practical issue, I thought that the second could be better is that perhaps searches could be slightly faster if the ID of the node is meaningful, but perhaps this is not good enough reason.
And I do like the argument about age, when I think about this more, that could be perhaps important if we have some data updates for all the tissues etc.?

**Comment by satra** [comment]
We don't have to necessarily. In the case of tissue, that is the `only` identity provider we know of at the moment. And I think the biolink model already has xref for other identifiers of the same entity.  

Searches could be made efficient in other ways, and will also depend on the connectivity structure of the graph.

**Comment by tekrajchhetri** [comment]
As of December 09, following the above discussion, we (@tekrajchhetri, @puja-trivedi and @djarecka) agreed to with **_representation 1_** and closing the issue.
